services:
  nginx:
    container_name: webserver
    build: 
      context: .docker/nginx
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./shop-api:/var/www/shop-api
      - .docker/nginx/shop.conf:/etc/nginx/conf.d/shop.conf:ro
    networks:
      - default
      - infrastructure
  php-fpm:
    container_name: shop-api
    build: 
      context: .
      dockerfile: .docker/php-fpm/shop-api/Dockerfile
    volumes:
      - ./shop-api:/var/www/shop-api
    networks:
      - default
      - infrastructure
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: shop_db
      MYSQL_USER: shop
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - .docker/mariadb/data:/var/lib/mysql
    networks:
      - infrastructure
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - infrastructure
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - infrastructure
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - infrastructure

networks:
  infrastructure:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16